# Generated by Django 6.0.1 on 2026-02-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество добавляемого товара'),
        ),
    ]
