# Generated by Django 6.0.1 on 2026-03-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="card_holder_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ФИО держателя карты"
            ),
        ),
    ]
