# Generated by Django 6.0.1 on 2026-03-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_card_holder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_holder_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ФИО держателя карты'),
        ),
    ]
