# Generated by Django 6.0.1 on 2026-02-16 13:09

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.CreateModel(
            name='ImagesProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(blank=True, null=True, upload_to=users.models.profile_avatar_upload_to_path, verbose_name='Ссылка на к файлу изображения')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Текстовое описание изображения')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.profile', verbose_name='Связь один к одному с моделью Profile')),
            ],
        ),
    ]
