# Generated by Django 6.0.1 on 2026-02-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Доступен ли товар, архивация'),
        ),
    ]
