# Generated by Django 6.0.1 on 2026-02-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='archived',
            field=models.BooleanField(default=False, help_text='Если включено, товар считается архивным и не отображается в каталоге для покупателей', verbose_name='Архивация товара (скрыт/доступен для продажи)'),
        ),
    ]
