# Generated by Django 6.0.1 on 2026-02-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_is_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_from',
            field=models.DateField(verbose_name='Дата начала акции\\скидки'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_to',
            field=models.DateField(verbose_name='Дата конца акции\\скидки'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='value',
            field=models.CharField(max_length=1500, verbose_name='Полная характеристика товара'),
        ),
    ]
