# Generated by Django 6.0.1 on 2026-02-10 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_sale_date_from_alter_sale_date_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
