# Generated by Django 6.0.1 on 2026-02-11 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='products.product', verbose_name='Связь с моделью продуктов, один к одному'),
        ),
    ]
