# Generated by Django 6.0.1 on 2026-02-24 12:19

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0015_alter_sale_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU')),
                ('delivery_type', models.CharField(blank=True, max_length=20, verbose_name='тип доставки')),
                ('payment_type', models.CharField(blank=True, max_length=20, verbose_name='способ оплаты')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(blank=True, default='pending', max_length=20)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количество товара в заказе')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена товара на момент покупки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
    ]
