# Generated by Django 6.0.1 on 2026-02-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, default='online', max_length=20, verbose_name='способ оплаты'),
        ),
    ]
