# Generated by Django 6.0.1 on 2026-03-06 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_deliverysettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverysettings',
            options={'verbose_name': 'Настройка доставки', 'verbose_name_plural': 'Настройки доставки'},
        ),
    ]
