# Generated by Django 6.0.1 on 2026-03-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_deliverysettings_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ordinary", "Обычная доставка - 200р"),
                    ("express", "Быстрая доставка - 500 р"),
                ],
                default="ordinary",
                max_length=20,
                verbose_name="тип доставки",
            ),
        ),
    ]
