# Generated by Django 6.0.1 on 2026-01-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('image', models.ImageField(upload_to='products/')),
                ('is_limited', models.BooleanField(default=False, verbose_name='Лимитированный продукт')),
                ('sorting_index', models.IntegerField(default=0, verbose_name='порядок сортировки')),
                ('purchases_count', models.IntegerField(default=0, verbose_name='количество покупок')),
                ('is_active', models.BooleanField(default=False, verbose_name='Доступность продукта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
